@url=http://localhost:5066
@json=Content-Type: application/json
### 登录
post {{url}}/api/users/login
{{json}}

{
    "username":"user_test_001",
    "password":"1234567890"
}

### 注册
post {{url}}/api/users/register
{{json}}

{
    "username":"user_test_001",
    "email":"test_001@email.com",
    "password":"1234567890"
}

### 测试获取信息
get {{url}}/api/users/testinfo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk3NzFjZDE4LTBhZjktNDA1Zi1iYTU3LWU2MDlkNTdmZmYwMyIsImlhdCI6MTc2MTI2ODgzMH0.RnLaHsKaGLC64upiED6GvCSar-UvLjnHg5g8o7PE3A4
