@url=http://localhost:5066
@json=Content-Type: application/json
### 登录
post {{url}}/api/users/login
{{json}}

{
    "username":"yangxingchen",
    "password":"123456yxc"
}

### 注册
post {{url}}/api/users/register
{{json}}

{
    "username":"TEST2",
    "email":"3@email.com",
    "password":"tes12323"
}
